#ifndef CYR_TOKS
#define DEFAULT_DEF
#define CYR_TOKS(x)
#endif

CYR_TOKS(TOK_EOF)
CYR_TOKS(TOK_IDENT)
CYR_TOKS(TOK_INT)
CYR_TOKS(TOK_PLUS)
CYR_TOKS(TOK_MINUS)
CYR_TOKS(TOK_COMMA)
CYR_TOKS(TOK_COLON)
CYR_TOKS(TOK_LBRACE)
CYR_TOKS(TOK_RBRACE)
CYR_TOKS(TOK_LBRACKET)
CYR_TOKS(TOK_RBRACKET)
CYR_TOKS(TOK_DOTDOT)
CYR_TOKS(TOK_KEYWORD_VARS)
CYR_TOKS(TOK_KEYWORD_SET)
CYR_TOKS(TOK_KEYWORD_YOSORO)
CYR_TOKS(TOK_KEYWORD_IHU)
CYR_TOKS(TOK_KEYWORD_HOR)
CYR_TOKS(TOK_KEYWORD_WHILE)
CYR_TOKS(TOK_KEYWORD_INT)
CYR_TOKS(TOK_KEYWORD_ARRAY)
CYR_TOKS(TOK_CMP_LT)
CYR_TOKS(TOK_CMP_GT)
CYR_TOKS(TOK_CMP_NEQ)
CYR_TOKS(TOK_CMP_PLACEHOLDER)
CYR_TOKS(TOK_CMP_GE)
CYR_TOKS(TOK_CMP_LE)
CYR_TOKS(TOK_CMP_EQ)

#ifdef DEFAULT_DEF
#undef DEFAULT_DEF
#undef CYR_TOKS
#endif